const mongoose=require('mongoose'),Admin=require('./Admin'),Customer=require('./Customer'),DeliveryBoy=require('./DeliveryBoy');
const base={id:{type:String,required:true,unique:true,index:true}};
const categorySchema=new mongoose.Schema({...base,name:{type:String,required:true,unique:true}},{timestamps:true,strict:false});
const productSchema=new mongoose.Schema({...base,name:{type:String,required:true},categoryId:String,price:Number,stock:Number,active:{type:Boolean,default:true}},{timestamps:true,strict:false});
const orderSchema=new mongoose.Schema({...base,customerId:{type:String,required:true,index:true},deliveryBoyId:{type:String,index:true},items:[{productId:String,name:String,price:Number,quantity:Number}],address:String,paymentMode:String,paymentStatus:{type:String,default:'pending'},bookingCharge:mongoose.Schema.Types.Mixed,status:String,subtotal:Number,deliveryCharge:Number,total:Number,receivedAmount:Number,paymentReceivedMode:String,deliveredAt:Date},{timestamps:true,strict:false});
const offlineBillSchema=new mongoose.Schema({billNo:{type:String,required:true,unique:true,index:true},customer:{name:String,phone:String,id:String},customerId:String,phone:String,items:[{productId:String,barcode:String,productName:String,category:String,unit:String,quantity:Number,mrp:Number,discount:Number,price:Number,amount:Number}],totalMrp:Number,totalDiscount:Number,itemTotal:Number,deliveryCharge:Number,handlingCharge:Number,totalAmount:Number,paidAmount:Number,remainingAmount:Number,paymentMethod:String,createdBy:String},{timestamps:true,strict:false,collection:'offline_bills'});
const Category=mongoose.models.Category||mongoose.model('Category',categorySchema),Product=mongoose.models.Product||mongoose.model('Product',productSchema),Order=mongoose.models.Order||mongoose.model('Order',orderSchema),OfflineBill=mongoose.models.OfflineBill||mongoose.model('OfflineBill',offlineBillSchema);
const nextId=async(Model,prefix)=>{const last=await Model.findOne({id:new RegExp(`^${prefix}`)}).sort({id:-1}).lean();return `${prefix}${String((Number(last?.id?.slice(prefix.length))||0)+1).padStart(3,'0')}`};
const nextCustomerId=async()=>{const customers=await Customer.find({id:/^DC-\d+$/},{id:1}).lean(),largest=customers.reduce((max,customer)=>{const value=Number(String(customer.id).slice(3));return Number.isInteger(value)?Math.max(max,value):max},-1);return `DC-${String(largest+1).padStart(6,'0')}`};
const modelForRole=role=>({admin:Admin,customer:Customer,delivery:DeliveryBoy}[role]);
async function findAccountById(id,role){const Model=modelForRole(role);if(!Model)return null;const query={id};if(role==='admin')query.role='admin';return Model.findOne(query)}
async function accountExists({phone,email}){const conditions=[];if(phone)conditions.push({phone:String(phone)});if(email)conditions.push({email:String(email).toLowerCase()});if(!conditions.length)return false;const query={$or:conditions},matches=await Promise.all([Admin.exists(query),Customer.exists(query),DeliveryBoy.exists(query)]);return matches.some(Boolean)}
async function migrateLegacyUsers(){const legacy=mongoose.connection.db.collection('users'),records=await legacy.find({role:{$in:['admin','customer','delivery']}}).toArray();for(const record of records){const Model=modelForRole(record.role);if(!Model||await Model.exists({id:record.id}))continue;const account={id:record.id,name:record.name,email:record.email,phone:record.phone,password:record.password,address:record.address,vehicleNo:record.vehicleNo,licenceNo:record.licenceNo,aadhaar:record.aadhaar,status:record.status,createdAt:record.createdAt,updatedAt:record.updatedAt};await Model.create(account)}if(records.length)console.log(`Migrated legacy user records into role-based collections`)}
async function migrateCustomerIds(){const customers=await Customer.find({id:{$not:/^DC-\d{6}$/}}).sort({createdAt:1,_id:1});for(const customer of customers){const previousId=customer.id,nextId=await nextCustomerId();customer.id=nextId;await customer.save();await Order.updateMany({customerId:previousId},{customerId:nextId})}if(customers.length)console.log(`Standardized ${customers.length} customer ID${customers.length===1?'':'s'} to DC-000000 format`)}
async function seed(){await migrateLegacyUsers();await migrateCustomerIds();const bcrypt=require('bcryptjs');await Admin.updateMany({role:'admin',status:{$exists:false}},{$set:{status:'Active'}});await Admin.updateMany({role:'admin',planType:{$exists:false}},{$set:{planType:'Lifetime',expiryDate:null}});if(!await Admin.exists({email:'admin@delhicanteen.com'}))await Admin.create({id:'ADM001',name:'Delhi Canteen Admin',email:'admin@delhicanteen.com',phone:'9999999999',password:await bcrypt.hash('admin123',10),shopName:'Delhi Canteen',planType:'Lifetime',status:'Active'})}
async function connect(){const uri=process.env.MONGODB_URI;if(!uri)throw new Error('MONGODB_URI is required. Add it to backend/.env');await mongoose.connect(uri,{serverSelectionTimeoutMS:5000});await seed();console.log('MongoDB connected');}
module.exports={connect,Admin,Customer,DeliveryBoy,Category,Product,Order,OfflineBill,nextId,nextCustomerId,modelForRole,findAccountById,accountExists};
